name: Scheduled API Call

on:
  schedule:
    - cron: "*/1 * * * *"  # Every 1 minutes (UTC time)
  workflow_dispatch:       # Allows manual trigger from the GitHub UI

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Make API Request
        run: |
          curl -X GET "https://httpbin.org/get"
