name: GitHub Actions Demo
run-name: Testing build

on:
  pull_request:
    branches: 
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['22.x']
    steps:
        - name: "Build Test"
          working-directory: ${{ github.workspace }}
          run: |
            npm i
        - run: |
            npm run build