name: GitHub Actions Demo
run-name: Testing build

strategy:
    matrix:
        node_version: ['22.x']


on: [pull_request]
    branches: 
        - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: "Build Test"
        - run: "npm ci"
        - run: "npm run build"